produce data

In [132]:
import numpy as np
n = 10 # 10 samples
m = 8  # 8 features
K = 6  # 6 principal features
X=np.random.rand(n,m)
C = X.T.dot(X)/n #covariance

power iteration method

In [133]:
def power_iteration(C):
    ev = np.random.rand(k+1,m) #eigen vector
    value = np.random.rand(k+1,1) #eigen value 
    for j in range(1,k+1):
        ev[j,:]=C.dot(ev[j-1,:])/np.linalg.norm(C.dot(ev[j-1,:]))
        value[j]=ev[j,:].T.dot(C).dot(ev[j,:])
    return ev[k,:],value[k]

sort the eigen vectors using eigen values

In [134]:
def eigen(A):
    eigenValues, eigenVectors = np.linalg.eig(A)
    idx = np.argsort(eigenValues)[::-1][:K]
    eigenValues = eigenValues[idx]
    eigenVectors = eigenVectors[:,idx]
    return (eigenValues, np.abs(eigenVectors))

In [135]:
ev,value = power_iteration(C)
print('eigen vector of power iteration:\n\n',ev,'\n')
e_value, e_vector = eigen(C)
print('true eigen vector:\n\n',e_vector[:,0])

eigen vector of power iteration:

 [0.3509208  0.20692545 0.37223282 0.39268898 0.45228703 0.38673417
 0.27821748 0.33127435] 

true eigen vector:

 [0.3509208  0.20692545 0.37223282 0.39268898 0.45228703 0.38673417
 0.27821748 0.33127435]


In [141]:
eigen_value=[]
eigen_vector = np.zeros((m,K))
v_vT = np.zeros((m,m))
C = X.T.dot(X)/n #covariance
for i in range(K):
    eigen_vec, eigen_val = power_iteration(C)
    eigen_value.append(eigen_val)
    eigen_vector[:,i] = eigen_vec

    for i in range(m):
        for j in range(m):
            v_vT[i,j]=eigen_vec[i]*eigen_vec[j]
    
    C -= eigen_val*v_vT

print('\n eigen vector from power iteration:\n',np.abs(eigen_vector))
print('\n true eigen vector:\n ',e_vector)
print('\n eigen value:\n',np.array(eigen_value))


 eigen vector from power iteration:
 [[0.3509208  0.24590779 0.68306332 0.27721421 0.05149003 0.1011549 ]
 [0.20692545 0.22444449 0.3500567  0.14344778 0.56098041 0.5590234 ]
 [0.37223282 0.04180991 0.25573064 0.39986935 0.50279693 0.48509078]
 [0.39268898 0.64726301 0.4288212  0.01001249 0.4676073  0.03207827]
 [0.45228703 0.23156359 0.01672422 0.34454471 0.0965951  0.65334739]
 [0.38673417 0.04259729 0.12350647 0.69092948 0.30879901 0.11766624]
 [0.27821748 0.08189117 0.27987409 0.33744697 0.27555701 0.01335739]
 [0.33127435 0.63742778 0.26026134 0.18059406 0.17484083 0.00564486]]

 true eigen vector:
  [[0.3509208  0.22219026 0.69555573 0.27087947 0.02002863 0.10533857]
 [0.20692545 0.23551912 0.34121114 0.17316057 0.37857279 0.70723898]
 [0.37223282 0.05165286 0.26349486 0.3732189  0.62136896 0.31308131]
 [0.39268898 0.66080428 0.3974936  0.00161589 0.46229542 0.10728365]
 [0.45228703 0.23106364 0.00697906 0.35009158 0.24136524 0.60836445]
 [0.38673417 0.04036017 0.12139421 0.7049